// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMAHiWZ4N0S42lJMalKrSnB91H7dHuMA4',
    appId: '1:763210927400:web:db2be86a3647f1a255541d',
    messagingSenderId: '763210927400',
    projectId: 'reddit-clone-c03d1',
    authDomain: 'reddit-clone-c03d1.firebaseapp.com',
    storageBucket: 'reddit-clone-c03d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVWWJ1ncMxlVs51rS4vFqNKWkseDwEyUM',
    appId: '1:763210927400:android:08f1fdbd2cb5488f55541d',
    messagingSenderId: '763210927400',
    projectId: 'reddit-clone-c03d1',
    storageBucket: 'reddit-clone-c03d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu7LcYVDE8kPm-V_kIrkB8q-3KyyamvgY',
    appId: '1:763210927400:ios:1572379496a5630755541d',
    messagingSenderId: '763210927400',
    projectId: 'reddit-clone-c03d1',
    storageBucket: 'reddit-clone-c03d1.firebasestorage.app',
    iosBundleId: 'com.example.redditClone',
  );
}
